music_directory     "/music/usb"
db_file             "/var/lib/mpd/database"
log_file            "/var/log/mpd/mpd.log"
pid_file            "/run/mpd/mpd.pid"
state_file          "/var/lib/mpd/state"

user                "root"
bind_to_address     "0.0.0.0"
port                "6600"

auto_update         "yes"
auto_update_depth   "0"

decoder {
    plugin          "ffmpeg"
    enabled         "yes"
}

audio_output {
    type            "pulse"
    name            "balena-sound"
    sink            "balena-sound.input"
}

input {
    plugin          "curl"
}
